mqtt:
  server: mqtts://10.117.165.202:18883
  servername: 192.168.137.51
  username: "wq"
  password: "1234"
  clientId: "test"
  certification: ../res/client.crt
  privatekey: ../res/client.key
  caCert: ../res/ca.crt
http:
  certification: ""
  privatekey: ""
  caCert: ""
configmap: ../res/mqtt.json
