mqtt:
  server: mqtts://192.168.137.51:8883
  servername: 192.168.137.51
  username: "wq"
  password: "1234"
  clientId: ""
  certification: ../res/client.pem
  privatekey: ../res/client.key
  caCert: ../res/ca.pem
http:
  certification: ../res/server.pem
  privatekey: ../res/server.key
  caCert: ../res/httpca.pem
configmap: ../res/virtual_device_test.json
