mqtt:
  server: mqtt://192.168.137.51:1883
  servicename: 192.168.137.51
  username: "wq"
  password: "1234"
  certification: ../res/client.pem
  privatekey: ../res/client.key
  caCert: ../res/ca.pem
http:
  certification: ../res/server.pem
  privatekey: ../res/server.key
  caCert: ../res/httpca.pem
configmap: ../res/configmap_test.json
