mqtt:
  server: mqtt://127.0.0.1:11883
  servername: 127.0.0.1
  username: ""
  password: ""
  clientId: ""
  certification: ""
  privatekey: ""
  caCert: ""
http:
  certification: ""
  privatekey: ""
  caCert: ""
configmap: ../res/virtual_device_test.json
